apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowhale
  namespace: test-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: tawsif93/hellowhale
        imagePullPolicy: Always
        name: hellowhale
        ports:
        - containerPort: 80
          name: 80tcp300051
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      restartPolicy: Always
      securityContext: {}
  replicas: 1
